### ISSUE TITLE
DiceDataset_20181214.zip/DiceDataset/4/00208.bmp が "5" のようです

### ISSUE THREAD

**Issue by ksasao** [tomitomi3/DiceRecognitionDatasetForML#3]
データセットの公開ありがとうございます。

4のフォルダに5のデータが混入しているようです。

```DiceDataset_20181214.zip``` 内の ```DiceDataset/4/00208.bmp```

ご確認ください。

**Comment by tomitomi3** [comment]
@ksasao ありがとうございます。修正しました。
